### ISSUE TITLE
Modal Pós Prova

### ISSUE THREAD

**Issue by Vitormdias** [IC-TestIt/Front-End#75]
Hoje quando o aluno termina a prova, não acontece nada, é interessante criar uma modal que tenha botões que possam redirecionar o aluno a tela de provas ou a home

**Comment by ivanfrias** [comment]
Viva, eu posso tratar desta funcionalidade.

**Comment by ivanfrias** [comment]
Como faço para entrar como aluno ?

**Comment by Vitormdias** [comment]
Pode usar:
vitormd97@gmail.com
senha@123

Tem que trocar no config dev pra apontar pra url da API de produção, porque ele ta apontando pro localhost

**Comment by ivanfrias** [comment]
Hmm. Fiz npm run build e depois corri node server.js dentro de /dist, suponho que a aplicação já está a apontar para PROD. O use-case que pretendo desenvolver implica conseguir fazer uma prova. Esse utilizador n tem prova ( ou pelo menos nas Avaliações a lista está vazia ). Como posso fazer para começar uma prova ?

![captura de ecra 2017-10-07 as 19 00 02](https://user-images.githubusercontent.com/4195447/31310550-c9f209a0-ab91-11e7-9569-cc4e347da9da.png)

**Comment by Vitormdias** [comment]
Então na home vc cadastra um professor, acho q o mais fácil é criar um usuário seu como professor, criar uma turma e depois colocar esse aluno nessa turma, depois é só criar prova e associar ela a turma que voce quer, se vc colocar uma prova no intervalo de tempo pro futuro, ela ira aparecer na tela de avaliações

**Comment by ivanfrias** [comment]
:+1:

**Comment by ivanfrias** [comment]
![captura de ecra 2017-10-07 as 20 46 17](https://user-images.githubusercontent.com/4195447/31311273-a429f30e-aba0-11e7-93ad-3f37c440a019.png)

Bug ? Cliquei em 'Criar Turma' e apareceu essa lista.

**Comment by Vitormdias** [comment]
Bug, era pra aparecer o form pra vc adicionar o aluno @Medson10 sabe oq é?

**Comment by medson10** [comment]
Não, versão do repositório e do heroku tão normal. Tamanho da tela talvez, veja se ele não ta renderizando o  form em lugar errado.

**Comment by Vitormdias** [comment]
@ivanfrias conseguiu adicionar o aluno?

**Comment by ivanfrias** [comment]
Hey! Sim já consegui, estou com um problema a aplicar a prova .. A janela fecha demasiado rápido. Mas irei resolver isso.

**Comment by ivanfrias** [comment]
Podem adicionar-me como developer ? 

remote: Permission to IC-TestIt/Front-End.git denied to ivanfrias.
fatal: unable to access 'https://github.com/IC-TestIt/Front-End.git/': The requested URL returned error: 403.

O bug do 'Aplicar prova' está resolvido e queria fazer commit para o branch.

**Comment by Vitormdias** [comment]
Acho mais fácil vc fazer um fork do repositório, e abrir um pull request

**Comment by Vitormdias** [comment]
É o fluxo que a gente usa aqui, ai o padrão de branch ta la no README

**Comment by ivanfrias** [comment]
Ok, feito,
Algum problema no back-end ? Não consigo fazer login na aplicação. O endpoint no ficheiro *.dev está correto e aponta para o site de PRD.

**Comment by Vitormdias** [comment]
http://ic-testit.azurewebsites.net/api/

Ta tudo normal aqui, se vc atualizar o projeto agora a gente ta usando o yarn e a gente fez umas mudanças pra rodar também, dai é usar npm start que vai apontar pra PROD
